@startuml
skinparam class {
BackgroundColor AliceBlue
ArrowColor DarkTurquoise
BorderColor Turquoise
}

skinparam stereotypeCBackgroundColor DarkTurquoise
skinparam stereotypeIBackgroundColor Magenta
skinparam stereotypeABackgroundColor Yellow

hide stereotype
hide empty member

abstract class AnalyseException

AnalyseException -up-|> RuntimeException

AnalyseLexicaleException -up-|> AnalyseException
AnalyseSyntaxiqueException -up-|> AnalyseException
AnalyseSemantiqueException -up-|> AnalyseException

class Analyse {
  -instance: Analyse
  Analyse()
  Analyse getInstance()
  ajoute(e: AnalyseSemantiqueException)
  ArrayList<AnalyseSemantiqueException> getList()
  setList(list: ArrayList<AnalyseSemantiqueException>)
}
Analyse --"1" Analyse
Analyse --"*" AnalyseSemantiqueException


abstract class ArbreAbstrait {
   int noLigne
   int numBloc
   protected ArbreAbstrait(int n, int num)
   void verifier()
   String toMIPS()
}

class BlocDInstructions {
   BlocDInstructions(int n,int num)
   void ajouter(Instruction i)
   void verifier()
   String toMIPS()
   Boolean contientRetourner()
   int numLigneRetourner()
}
class BlocFonctions {
}
class BlocMain{}

BlocDInstructions -up-|> ArbreAbstrait
BlocFonctions -up-|> BlocDInstructions
BlocMain -up-|> BlocDInstructions
BlocDInstructions -up- "*" Instruction

abstract class Instruction {
   protected Instruction(int n, int numbloc)
   abstract boolean estRetourner()
   abstract boolean estBoucleOuCondition();
   abstract boolean estCondition();
}

Instruction -up-|> ArbreAbstrait
class Ecrire {
    int numero
   Ecrire(Expression e, int n, int num)
   void verifier()
   String toMIPS()
   boolean estRetourner()
   boolean estBoucleOuCondition()
   Boolean contientRetourner()
   boolean estCondition() 
}
class Retourne{
   int num
   Retourne(Expression e, int n, int num)
   void verifier()
   String toMIPS()
   boolean estRetourner()
}

class Boucle{
 Boucle(int n, int numBloc, ArbreAbstrait a, Expression e) 
 void verifier()
 String toMIPS() 
 String derouleMips(BlocDInstructions b)
 boolean estRetourner()
 boolean estBoucleOuCondition()
  boolean contientRetourner()
  boolean estCondition()
}
Boucle --"1" BlocDInstructions
Boucle --"1" Expression

class Condition{
Condition(int n, int numBloc, Expression e, ArbreAbstrait a, ArbreAbstrait a1)
void verifier() 
 String toMIPS()
 String derouleMips(BlocDInstructions b)
 boolean estRetourner()
 boolean estBoucleOuCondition()
 Boolean contientRetourner()
  boolean estCondition()
}
Condition --"2" BlocDInstructions
Condition--"1" Expression

Ecrire  -up-|> Instruction
Retourne  -up-|> Instruction
Boucle -up-|> Instruction
Condition  -up-|> Instruction

abstract class Expression {
   protected Expression(int n)
   Type getType()
   boolean estVariable()
   boolean estBool()
   boolean estFonction()
   String getIdf()
}

Expression  -up-|> ArbreAbstrait
Ecrire - "1" Expression

abstract class Constante {
   String cste
   protected Constante(String texte, int n)
   void verfier()
   boolean estVariable()
   Symbole getSymbole()
   Type getType()
   String getIdf()
}

Constante  -up-|> Expression

class ConstanteEntiere {
   ConstanteEntiere(String texte, int n)
   String toMIPS()
   boolean estVariable()
   boolean estBool()
   boolean estFonction()
   Type getType()
}

class ConstanteBooleenne {
   ConstanteBooleenne(String texte, int n)
   String toMIPS()
   boolean estVariable()
   boolean estBool()
   boolean estFonction()
   Type getType()
}
class AppelFonction {
   String idf;
   AppelFonction(String idf,int n)
   String toMIPS()
   boolean estVariable()
   boolean estBool()
   boolean estFonction()
   Symbole getSymbole()
   Type getType()
   String getIdf()
}
AppelFonction  -up-|> Expression

abstract class Binaire{
 Binaire(int n, int num, Expression e1, Expression e2) 
  abstract void verifier()
}
Binaire  -up-|> Expression
Binaire --"2" Expression


class Different{
 Different(int n, int num, Expression e1, Expression e2)
 boolean estBool()
 boolean estFonction()
 boolean estConstante()
  void verifier()
   boolean estBinaire()
   String toString()
   String toMIPS()
}
Different -up-|> Binaire

class Egale{
int numero
Egale(int n, int num, Expression e1, Expression e2)
boolean estBool()
boolean estFonction()
boolean estConstante()
void verifier()
boolean estBinaire()
String toMIPS()

}
Egale -up-|> Binaire


class Et{
Et(int n, int num, Expression e1, Expression e2) 
boolean estBool()
boolean estFonction()
boolean estConstante()
void verifier()
String toMIPS()
boolean estBinaire()
}
Et -up-|> Binaire

class Iferieur{
Inferieur(int n, int num, Expression e1, Expression e2) 
boolean estBool()
boolean estFonction()
boolean estConstante()
void verifier()
String toMIPS()
boolean estBinaire()
}
Inferieur -up-|> Binaire

class Multiplication{
Multiplication(int n, int num, Expression e1, Expression e2)
boolean estBool()
boolean estFonction()
boolean estConstante()
void verifier()
String toMIPS()
boolean estBinaire()
}
Multiplication -up-|> Binaire

class Ou{
Ou(int n, int num, Expression e1, Expression e2)
boolean estBool()
boolean estFonction()
boolean estConstante()
void verifier()
String toMIPS()
boolean estBinaire()
}
Ou -up-|> Binaire


class Somme{
Somme(int n, int num, Expression e1, Expression e2)
boolean estBool()
boolean estFonction()
boolean estConstante()
void verifier()
String toMIPS()
boolean estBinaire()
}
Somme -up-|> Binaire


abstract class Unaire{
Unaire(int n, int num, Expression e)
boolean estBinaire()
}
Unaire -up-|> Expression


class Negative{
 Negative(int n, int num,Expression e)
boolean estBool()
boolean estFonction()
boolean estConstante()
void verifier()
String toMIPS()
boolean estBinaire()
}
Negative -up-|> Unaire

class Non{
Non(int n, int num,Expression e)
boolean estBool()
boolean estFonction()
boolean estConstante()
void verifier()
String toMIPS()
boolean estBinaire()
}
Non -up-|> Unaire


class Parenthese{
 Parenthese(int n, int num,Expression e)
boolean estBool()
boolean estFonction()
boolean estConstante()
void verifier()
String toMIPS()
boolean estBinaire()
}
Parenthese -up-|> Unaire


class TDS {
int compteurDeplace
int noActuBloc
int noPrecBloc
TDS instance
TDS getInstance()
void ajouter (Entree e, Symbole s)
Symbole identifier(Entree e)
int getTailleZoneVariable()
void entreeBloc()
void sortieBloc()
}
class FabriqueNumero {
  int nb
  FabriqueNumero instance
  FabriqueNumero()
  FabriqueNumero getInstance()
  int genererNombre()
}
FabriqueNumero --"1" FabriqueNumero

abstract class Symbole{
String type
int deplacement
String getType()
int getDeplacement()
void setType(String type)
boolean estFonction()
}
class SymboleFonction{
 SymboleFonction(String type, ArbreAbstrait li)
 boolean estFonction()
}

SymboleFonction--"1"ArbreAbstrait

class SymboleVariable{
 SymboleVariable(String type)
 boolean estFonction()
}

TDS --"*" Symbole
Type --"1" Symbole

SymboleFonction  -up-|> Symbole
SymboleVariable  -up-|> Symbole


ConstanteEntiere  -up-|> Constante
ConstanteBooleenne  -up-|> Constante

enum Type{
ENTIER("entier")
BOOLEEN("booleen")
String type
Type(String type)
Type quelleType(String type)
Boolean concordance(Type type)
}

abstract class Entree{
String idf
int noLigne
Entree(String idf,int l)
}
class EntreeFonction{
EntreeFonction(String idf, int l)
boolean estFonction()
}
class EntreeVariable{
EntreeVariable(String idf, int l)
boolean estFonction()
}

EntreeVariable  -up-|> Entree
EntreeFonction  -up-|> Entree



class Affectation {
Affectation(String idf, Expression e, int n)
void verifier()
String toMIPS()
boolean estRetourner()
}
Affectation --"1" Idf
Affectation --"1" Expression
Affectation  -up-|> Instruction

class Idf{
String variable
Idf(String texte, int n)
void verifier()
String toMIPS()
Symbole getSymbole()
boolean estVariable()
boolean estBool()
boolean estFonction()
String getIdf()
}
Idf --|> Expression
@enduml
