
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 31 23:00:32 CET 2023
//----------------------------------------------------

package zoot.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int ECRIRE = 6;
  public static final int IDF = 9;
  public static final int EGALE = 7;
  public static final int DEBUT = 3;
  public static final int POINTVIRGULE = 5;
  public static final int FIN = 4;
  public static final int EOF = 0;
  public static final int VARIABLES = 2;
  public static final int TYPE = 10;
  public static final int error = 1;
  public static final int CSTENTIERE = 8;
}

