
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 14 23:07:05 CEST 2023
//----------------------------------------------------

package zoot.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int RETOURNE = 11;
  public static final int IDF = 30;
  public static final int JUSQUA = 27;
  public static final int CSTENTIERE = 29;
  public static final int OU = 21;
  public static final int ECRIRE = 6;
  public static final int SOUS = 14;
  public static final int ALORS = 28;
  public static final int AFF = 7;
  public static final int FONCTIONS = 8;
  public static final int VIRGULE = 12;
  public static final int REPETER = 24;
  public static final int NON = 13;
  public static final int OUVRE = 9;
  public static final int INF = 17;
  public static final int POINTVIRGULE = 5;
  public static final int SINON = 23;
  public static final int TYPE = 31;
  public static final int EGALE = 18;
  public static final int VARIABLES = 2;
  public static final int FINREPETER = 25;
  public static final int FERME = 10;
  public static final int EOF = 0;
  public static final int MULT = 16;
  public static final int CSTBOOLEEN = 32;
  public static final int ADD = 15;
  public static final int SI = 22;
  public static final int ET = 20;
  public static final int error = 1;
  public static final int DIFF = 19;
  public static final int DEBUT = 3;
  public static final int FINSI = 26;
  public static final int FIN = 4;
}

