
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 24 23:25:25 CET 2023
//----------------------------------------------------

package zoot.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int FONCTIONS = 8;
  public static final int ECRIRE = 6;
  public static final int IDF = 12;
  public static final int RETOURNE = 10;
  public static final int EGALE = 7;
  public static final int DEBUT = 3;
  public static final int CSTBOOLEEN = 14;
  public static final int POINTVIRGULE = 5;
  public static final int FIN = 4;
  public static final int EOF = 0;
  public static final int VARIABLES = 2;
  public static final int TYPE = 13;
  public static final int error = 1;
  public static final int CSTENTIERE = 11;
  public static final int PARENTHESE = 9;
}

